# Port du serveur
server.port=9191

# Activation de la découverte automatique des routes via Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Routes pour Agriculture_User microservice
spring.cloud.gateway.routes[0].id=agriculture-auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=agriculture-user-service
spring.cloud.gateway.routes[1].uri=lb://agriculture-user
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/user/**

spring.cloud.gateway.routes[2].id=agriculture-culture-service
spring.cloud.gateway.routes[2].uri=lb://gestion-culture-server
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/cultures/**

spring.cloud.gateway.routes[3].id=agriculture-parcelle-service
spring.cloud.gateway.routes[3].uri=lb://gestion-parcelle-cartography-server
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/parcelles/**

spring.cloud.gateway.routes[4].id=agriculture-recolte-service
spring.cloud.gateway.routes[4].uri=lb://gestion-recolte-server
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/recoltes/**

spring.cloud.gateway.routes[5].id=agriculture-profile-service
spring.cloud.gateway.routes[5].uri=lb://agriculture-user
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/profiles/**



# Routes pour le service IA Prediction
spring.cloud.gateway.routes[6].id=agriculture-ia-service
spring.cloud.gateway.routes[6].uri=http://localhost:8095
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/diagnostics/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1


# Routes pour le service Profile individuel (via Agriculture_User)
spring.cloud.gateway.routes[7].id=agriculture-profile-individual-service
spring.cloud.gateway.routes[7].uri=lb://agriculture-user
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/profile/**


