# Activation de la découverte automatique des routes via Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Définition manuelle d'une route pour Agriculture_User
spring.cloud.gateway.routes[0].id=agriculture-user-service
spring.cloud.gateway.routes[0].uri=lb://Agriculture_User
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user/**
