# Configuration Cloud Config
spring.application.name=Gestion-MaquettePlace-server
server.port=8084

# Configuration MongoDB
spring.data.mongodb.uri=mongodb://admin:${MONGO_PASSWORD:admin123}@mongodb:27017/market_db?authSource=admin
spring.data.mongodb.database=market_db

# Configuration Feign
feign.client.config.default.connect-timeout=86400
feign.client.config.default.read-timeout=86400


# JWT configuration
app.jwt.secret=hF9IsSdyj/KnkZiAJsAnwKsf4rJombf3MAX4pZFBzql8WQyPFy8gVSGxUyTaT3m4gE9yG+i1KGz5BpP5k8+jgg==
app.jwt.expiration=3600000



# Configuration Eureka
# Local Eureka settings (if running locally)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# DÃ©sactiver la vÃ©rification de compatibilitÃ© Spring Cloud
spring.cloud.compatibility-verifier.enabled=false
